// <auto-generated />
using System;
using EAVStore.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace EAVStore.DataAccess.Migrations
{
    [DbContext(typeof(EavStoreDbContext))]
    partial class EavStoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("EAVStore.DataAccess.Entities.AttributeValueEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AttributeType");

                    b.Property<Guid?>("EntityId");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.ToTable("AttributeValues");
                });

            modelBuilder.Entity("EAVStore.DataAccess.Entities.EavEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("EntityType");

                    b.HasKey("Id");

                    b.ToTable("Entities");
                });

            modelBuilder.Entity("EAVStore.DataAccess.Entities.AttributeValueEntity", b =>
                {
                    b.HasOne("EAVStore.DataAccess.Entities.EavEntity", "Entity")
                        .WithMany("AttributeValues")
                        .HasForeignKey("EntityId");
                });
#pragma warning restore 612, 618
        }
    }
}
